<?php

/**
 * @file
 * Contains groups.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function groups_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the groups module.
    case 'help.page.groups':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for groups') . '</p>';
      return $output;

    default:
  }
}
